version: '3'
services:
  web:
    image: nginx:1.19
    container_name: baby_diary_web
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php
      - db
  db:
    image: mariadb:10.5
    restart: always
    container_name: baby_diary_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    volumes:
      - "./docker/mysql:/var/lib/mysql"
      - "./docker/initdb.d:/docker-entrypoint-initdb.d"
  php:
    build: ./docker/php
    container_name: baby_diary_php
    depends_on: 
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
