version: '3'
services:
  web:
    build: ./docker/nginx
    container_name: baby_diary_web
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php
      - db
    # https://stackoverflow.com/questions/47577490/resolve-container-name-in-extra-hosts-option-in-docker-compose
    networks:
      web-network:
        aliases:
          - image.${APP_DOMAIN}

  db:
    image: mariadb:10.5
    restart: always
    container_name: baby_diary_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    container_name: baby_diary_php
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - web-network

  schemaspy-nginx:
    image: nginx:1.13.9-alpine
    container_name: schemaspy_nginx
    volumes:
      - ./docker/schemaspy/output:/var/www/html:ro
      - ./docker/schemaspy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8081:80'
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  schemaspy:
    build: ./docker/schemaspy
    image: treetips/schemaspy-mysql
    volumes:
      - ./docker/schemaspy/output:/app/html:rw
      - ./docker/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja.JP.UTF-8
      - TZ=Asia/Tokyo
    container_name: 'schemaspy_local'
    command: 'java -jar schemaspy.jar'
    working_dir: '/app'
    links:
      - db

  redoc:
    image: redocly/redoc
    ports:
      - '8003:80'
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      PAGE_TITLE: baby_diary api
      SPEC_URL: openapi.yml

  minio:
    image: minio/minio:latest
    ports: 
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /usr/bin/minio server /data;"
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/export:/export
      - ./docker/minio/config:/root/.minio
      - ./docker/minio/policies:/policies
    networks:
      web-network:

networks:
  web-network:
    driver: bridge