version: '3'
services:
  web:
    image: nginx:1.19
    container_name: baby_diary_web
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.5
    restart: always
    container_name: baby_diary_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    container_name: baby_diary_php
    depends_on: 
      - db
    volumes:
      - .:/var/www/html

  schemaspy-nginx:
    image: nginx:1.13.9-alpine
    container_name: schemaspy_nginx
    volumes:
      - ./docker/schemaspy/output:/var/www/html:ro
      - ./docker/schemaspy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  schemaspy:
    build: ./docker/schemaspy
    image: treetips/schemaspy-mysql
    volumes:
      - ./docker/schemaspy/output:/app/html:rw
      - ./docker/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
    environment: 
      - LANG=ja.JP.UTF-8
      - TZ=Asia/Tokyo
    container_name: "schemaspy_local"
    command: "java -jar schemaspy.jar"
    working_dir: "/app"
    links:
      - db
