name: pr

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: staging
          commit-message: test
