name: pr

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo ${{ github.sha }}
